services:
  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $PWD/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: tallerapi
      MYSQL_USER: admin
      MYSQL_PASSWORD: elden
      MYSQL_ROOT_PASSWORD: elden
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - net
  api:
    build: .
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_USER: 'admin'
      DB_PASSWORD: 'elden'
      DB_NAME: tallerapi
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 3000
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappserver
      TOKEN_SECRET: secreto
    networks:
      - net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - net
networks:
  net:
    driver: bridge
