export enum Status {
  OK = 'OK',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  CREATED = 'CREATED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}